version: '3.8'

services:
  web:
    build: .
    ports:
      - "8848:8848"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lang_portal
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lang_portal
    ports:
      - "5432:5432"

volumes:
  postgres_data:
